# Generated by Django 2.2.10 on 2021-07-25 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_name', models.CharField(max_length=40)),
                ('start_data', models.DateField(verbose_name='Start Data')),
                ('end_data', models.DateField(verbose_name='Start Data')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Description')),
                ('question_type', models.CharField(choices=[('TF', 'Ответ текстом'), ('SV', 'Один вариант'), ('FV', 'Выбор нескольких вариантов')], max_length=2)),
                ('parent_poll', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.Poll')),
            ],
        ),
    ]
