# Generated by Django 2.2.10 on 2021-07-31 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210731_0958'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
