# Generated by Django 3.2.6 on 2021-08-07 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_auto_20210803_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_text', models.TextField(verbose_name='Answer')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_user', to=settings.AUTH_USER_MODEL)),
                ('multiple_choice', models.ManyToManyField(null=True, related_name='multiple_choice', to='api.Choice')),
                ('parent_poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_poll', to='api.poll')),
                ('parent_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_question', to='api.question')),
                ('single_choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='single_choice', to='api.choice')),
            ],
        ),
    ]
