# Generated by Django 3.2.6 on 2021-08-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='multiple_choice',
            field=models.ManyToManyField(blank=True, related_name='multiple_choice', to='api.Choice'),
        ),
    ]
