# Generated by Django 3.2.6 on 2021-08-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polluser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
